services:
  postgres-vector:
    image: pgvector/pgvector:pg16
    container_name: mindbase-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mindbase_db
    ports:
      - "5432:5432"
    volumes:
      - mindbase_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: mindbase-ollama
    ports:
      - "11434:11434"
    volumes:
      - mindbase_ollama_data:/root/.ollama
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mindbase-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - mindbase_rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  mindbase_pgdata:
  mindbase_ollama_data:
  mindbase_rabbitmq_data: